bookmark_robot_meituan_tech:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'meituan_tech'
  queue: hardly
bookmark_robot_hackernews_best:
  cron: '0 0 1 * * *'
  class: BookmarkRobotJob
  args: 'hackernews_best'
  queue: hardly
bookmark_robot_manong_weekly:
  cron: '0 0 2 * 1'
  class: BookmarkRobotJob
  args: 'manong_weekly'
  queue: hardly
bookmark_robot_github_trending:
  cron: '0 0 3 * * *'
  class: BookmarkRobotJob
  args: 'github_trending'
  queue: hardly
bookmark_robot_wanqu:
  cron: '0 0 4 * * *'
  class: BookmarkRobotJob
  args: 'wanqu'
  queue: hardly
bookmark_robot_dribbble_popular:
  cron: '0 0 5 * * *'
  class: BookmarkRobotJob
  args: 'dribbble_popular'
  queue: hardly
bookmark_robot_v2ex_hot:
  cron: '0 0 6 * * *'
  class: BookmarkRobotJob
  args: 'v2ex_hot'
  queue: hardly
