bookmark_robot_meituan_tech:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'meituan_tech'
  queue: hardly
bookmark_robot_wanqu_daily:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'wanqu_daily'
  queue: hardly
bookmark_robot_dribbble:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'dribbble'
  queue: hardly
bookmark_robot_producthunt:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'producthunt'
  queue: hardly
bookmark_robot_hackernews:
  cron: '0 0 1 * * *'
  class: BookmarkRobotJob
  args: 'hackernews'
  queue: hardly
bookmark_robot_manong_weekly:
  cron: '0 0 2 * * *'
  class: BookmarkRobotJob
  args: 'manong_weekly'
  queue: hardly
bookmark_robot_github:
  cron: '0 0 3 * * *'
  class: BookmarkRobotJob
  args: 'github'
  queue: hardly
bookmark_robot_v2ex:
  cron: '0 0 4 * * *'
  class: BookmarkRobotJob
  args: 'v2ex'
  queue: hardly
