default: &default
  concurrency: 5
  queues:
    - [critical, 200]
    - [default, 100]
    - [seldom, 40]
    - [hardly, 5]
  schedule:
    bookmark_robot_meituan:
      cron: '0 0 16 * * *'
      class: BookmarkRobotJob
      args: '美团'
      queue: hardly
    bookmark_robot_hackernews:
      cron: '0 0 0 * * *'
      class: BookmarkRobotJob
      args: 'hackernews'
      queue: hardly
development:
  <<: *default
test:
  <<: *default
production:
  <<: *default
  concurrency: 20
