bookmark_robot_meituan_tech:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'meituan_tech'
  queue: hardly
bookmark_robot_wanqu_daily:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'wanqu_daily'
  queue: hardly
bookmark_robot_dribbble:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'dribbble'
  queue: hardly
bookmark_robot_producthunt:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'producthunt'
  queue: hardly
bookmark_robot_devto:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'devto'
  queue: hardly
bookmark_robot_rubyweekly:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'rubyweekly'
  queue: hardly
bookmark_robot_javascriptweekly:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'javascriptweekly'
  queue: hardly
bookmark_robot_golangweekly:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'golangweekly'
  queue: hardly
bookmark_robot_chaping:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'chaping'
  queue: hardly
bookmark_robot_ifanr:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'ifanr'
  queue: hardly
bookmark_robot_qdaily:
  cron: '0 0 0 * * *'
  class: BookmarkRobotJob
  args: 'qdaily'
  queue: hardly
bookmark_robot_hackernews:
  cron: '0 0 1 * * *'
  class: BookmarkRobotJob
  args: 'hackernews'
  queue: hardly
bookmark_robot_manong_weekly:
  cron: '0 0 2 * * *'
  class: BookmarkRobotJob
  args: 'manong_weekly'
  queue: hardly
bookmark_robot_github:
  cron: '0 0 3 * * *'
  class: BookmarkRobotJob
  args: 'github'
  queue: hardly
bookmark_robot_v2ex:
  cron: '0 0 4 * * *'
  class: BookmarkRobotJob
  args: 'v2ex'
  queue: hardly
bookmark_robot_bilibiliweekly:
  cron: '0 0 5 * * *'
  class: BookmarkRobotJob
  args: 'bilibiliweekly'
  queue: hardly
bookmark_robot_doubanweekly:
  cron: '0 0 6 * * *'
  class: BookmarkRobotJob
  args: 'doubanweekly'
  queue: hardly
bookmark_robot_zhihuhot:
  cron: '0 0 7 * * *'
  class: BookmarkRobotJob
  args: 'zhihuhot'
  queue: hardly
