name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README*.md'
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README*.md'
      - 'docs/**'

jobs:
  build:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle exec rubocop
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    env:
      ID_RSA: ${{ secrets.ID_RSA }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: |
        mkdir -p ~/.ssh/
        echo "$ID_RSA" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        bundle exec cap production deploy
        bundle exec cap production sitemap:refresh

  docker:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: |
            hooopo/hackershare:latest
          build-args: |
            SECRET_KEY_BASE=precompile_placeholder
            RAILS_ENV=production
