name: CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'README.md'
      - 'docs/**'

jobs:
  build:
    if: ${{ !contains(github.event.commits[0].message, '[skip ci]') }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run: bundle exec rubocop
  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: build
    env:
      ID_RSA: ${{ secrets.ID_RSA }}
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6
        bundler-cache: true
    - run: |
        mkdir -p ~/.ssh/
        echo "$ID_RSA" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        bundle exec cap production deploy
        bundle exec cap production sitemap:refresh
